### PR TITLE
Update to latest 1.19

### PR DESCRIPTION
**Pull request by bvhfve**
Updated to Fabric loader 0.14.9, FAPI 0.58.0, LibGui 6.1.0, Cardinal Components 5.0.2
Changed "version" to 3.0.1 ( you can change it back to 3.0.0 if you want)

### CODE REVIEW

**Comment by mrmelon54** [comment]
why did you change `${version}` to `3.0.1` in `fabric.mod.json`?

**Comment by bvhfve** [comment]
I thought it would make sense to change it because it's an updated version (I don't really understand the versioning policy, sorry if that annoyed you), you can change it back if you want : )

**Comment by mrmelon54** [comment]
you changed in it `gradle.properties` correctly, but you don't need to change `${version}` that gets populated in the build process

**Comment by bvhfve** [comment]
oh i thought i have done something wrong, okay -_-

**Comment by mrmelon54** [comment]
Closing as I have since completed the update to 1.19 on my own.

**Pull request closed without merging**
